### ISSUE TITLE
Malshare Toolkit options

### ISSUE THREAD

**Issue by nikhileshksingh** [Malshare/MalShare#15]
I have just now started using malshare toolkit. I am using it as,

wget_malshare_daily [-k APIKEY]  -d [-o OUTFOLDER] [-x VXCAGE]

I am getting errors regarding the last option. What is it expecting? I searched the web and found a few things but nothing that could help. Would someone please tell me what it is? #

**Comment by silascutler** [comment]
with VXChage?

**Comment by silascutler** [comment]
Closed
