### ISSUE TITLE
Open-sourcing

### ISSUE THREAD

**Issue by silascutler** [Malshare/MalShare#22]
Discussed in: https://twitter.com/adulau/status/1060910814692028417.

Opening this issue to track / evaluate

**Comment by silascutler** [comment]
This is being actively worked on.

**Comment by silascutler** [comment]
Announced for this month: https://twitter.com/mal_share/status/1138104636882202631

**Comment by silascutler** [comment]
The roll-out will happen in a couple stages.  The breakdown I have of parts are:

- Front-end / website code (Includes backend database // all real moving parts)
- Backend admin tools (these are mainly things like search for user by email or API key and admin status reports)
- Sample harvesting system
- Sample pipeline

The sample harvesting tools and admin tools may be partially released.  Most of these are scrappy and I'm sure others would rather write their own.

**Comment by adrenaline96** [comment]
Nice, looking forward to this. If I can help in any way please let me know. After the complete roll-out is done I will check my implementation of the API to see if it's still working.

**Comment by silascutler** [comment]
Code is now live
