### ISSUE TITLE
Feature Request: Filter Daily Digest by File Type

### ISSUE THREAD

**Issue by larsborn** [Malshare/MalShare#4]
Hey,
I currently got the use case where I am only interested in PE files and would like to consume new files from MalShare daily (also retroactively but this is probably a different story). I can - of course - download all files and delete those that are not interesting to me but this would probably waste a lot of your bandwidth.

So any chance that filtering the daily digest based on file type i.e. magic could be implemented?

Cheers
Lars

**Comment by Malshare** [comment]
Does the API call for listing hashes by type work for this? 
/ GET /api.php?api_key=[API_KEY]&action=type&type=[FILE TYPE] /

**Comment by Malshare** [comment]
Moved this output format also to JSON

**Comment by larsborn** [comment]
Oh yes, it contains a field called `F_TYPE` that is `PE32` for example. That would double the number of requests but at least save the bandwidth for the actual download. Looking forward to #7.

And thanks for the quick replies of course!!
