### ISSUE TITLE
Bug Report: HTTP error code in case of API rate limit

### ISSUE THREAD

**Issue by larsborn** [Malshare/MalShare#5]
Hey,

**observed behavior**: when performing too many API requests per day - say to https://malshare.com/api.php?api_key=KEY&action=details&hash=e63d848b43175a2635b595eea3a2ae47 - the error text
```
ERROR! => Over Request Limit. Please contact admin@malshare.com if you need this increased
```
is returned with a HTTP status code of `200`.

**expected behavior**: an error code of `429 Too Many Requests` for example.

I realize that this is not "decisive for the outcome of the war" (as we say in Germany, aka that this is low-priority) but it was a reason for me to not realizing that something was wrong (bug on my side).  And consequently I continue to send requests to the API - sorry for that of course!

Anyway: feel free to close this report without any changes. Just wanted to tell you at least.

Cheers
Lars

**Comment by Malshare** [comment]
Thanks for the issue.  I've added a HTTP 429 for over request limit.  Additionally, in places where errors occur, I've added a 500 error codes and when samples are missing, proper 404s.
