### ISSUE TITLE
archive passwords?

### ISSUE THREAD

**Issue by mattfj10** [Malshare/MalShare#73]
I've noticed that some samples are in an archive format (ZIP/7ZIP/RAR/ACE), and are often password protected. Is there a standard password associated with these archives (the industry standard 'infected' didn't seem to work), or if it's different for each archive a place to get the passwords that I missed? I didn't see any info about it in the reports when I query it back via the API or look up the individual sample on the web page. 

Thanks

**Comment by silascutler** [comment]
We don't add passwords to any of the files we've collected.  If there is a password, it's not one we know or added.
