### ISSUE TITLE
Support: Is Malshare still maintained ? 

### ISSUE THREAD

**Issue by Nicolas-Pellletier** [Malshare/MalShare#76]
Hello 

I was wondering if malshare is still maintained ? 
Because i can see on the home page that the recently added sample date back from 2022-12-22.
![image](https://github.com/Malshare/MalShare/assets/126868918/486aaab6-854a-4735-b36e-8f04af888947)

However when i see the Daily digest file i see some file for today

**Comment by PhilSchroeder** [comment]
+1, wondering the same thing

**Comment by aaykut** [comment]
^^ @silascutler  ?

**Comment by silascutler** [comment]
Yes.  We're working on a migration atm.
