### ISSUE TITLE
2023-11: Site Migration

### ISSUE THREAD

**Issue by silascutler** [Malshare/MalShare#77]
Disk issues have taken down the site again. Working on migration and rebuild

**Comment by silascutler** [comment]
After the rebuild in #19 , we've been primarily on a dedicated server at Hetzner.  Long term, we're going to keep burning through servers.  The structure of the site needs a re-architecture. We've tested parts of this before #42, however, it's time to move to a proper object store for samples.

Active tasks:
- [x] Backups underway (@larsborn, self, and long term s3 storage)
- [x] S3 option evaluation
- [ ] New server build

Pending
- [ ] Migrate Frontend to use object storage

**Comment by silascutler** [comment]
Storage server's crashed a few times as data is being moved.  It's a slow process, but we're moving along with migration

**Comment by silascutler** [comment]
Almost everything is off the old infrastructure.  New systems  will come online early next week

**Comment by HSp4m** [comment]
Sorry if I'm doing something wrong, but what happened?

**Comment by silascutler** [comment]
Site's back online

**Comment by silascutler** [comment]
> Sorry if I'm doing something wrong, but what happened?

Server at Hetzner started to have disk issues. We'd been working to keep it online, but with how we've grown, some key architectural changes were needed (like moving the sample collection to s3)
